// WARNING: This file has automatically been generated on Fri, 20 May 2022 19:39:49 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <cuse_lowlevel.h>
#include <fuse_lowlevel.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

