// WARNING: This file has automatically been generated on Thu, 19 May 2022 22:32:28 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <cuse_lowlevel.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// fuse_interrupt_func_t_a8cb1480 is a proxy for callback fuse_interrupt_func_t.
void fuse_interrupt_func_t_a8cb1480(fuse_req_t req, void* data);

// fuse_opt_proc_t_63352f8e is a proxy for callback fuse_opt_proc_t.
int fuse_opt_proc_t_63352f8e(void* data, char* arg, int key, struct fuse_args* outargs);

// fuse_log_func_t_d65c7516 is a proxy for callback fuse_log_func_t.
void fuse_log_func_t_d65c7516(enum fuse_log_level level, char* fmt, void* ap);

