// WARNING: This file has automatically been generated on Thu, 19 May 2022 22:32:28 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void fuse_interrupt_func_t_a8cb1480(fuse_req_t req, void* data) {
	interruptFuncA8CB1480(req, data);
}

int fuse_opt_proc_t_63352f8e(void* data, char* arg, int key, struct fuse_args* outargs) {
	return optProc63352F8E(data, arg, key, outargs);
}

void fuse_log_func_t_d65c7516(enum fuse_log_level level, char* fmt, void* ap) {
	logFuncD65C7516(level, fmt, ap);
}

