// WARNING: This file has automatically been generated on Fri, 20 May 2022 19:39:49 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cuse

/*
#cgo pkg-config: fuse3
#include <cuse_lowlevel.h>
#include <fuse_lowlevel.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// UseVersion as defined in webpipe/<predefine>:24
	UseVersion = 31
	// UnrestrictedIoctl as defined in fuse3/cuse_lowlevel.h:29
	UnrestrictedIoctl = (1 << 0)
	// RootId as defined in fuse3/fuse_lowlevel.h:43
	RootId = 1
	// SetAttrMode as defined in fuse3/fuse_lowlevel.h:131
	SetAttrMode = (1 << 0)
	// SetAttrUid as defined in fuse3/fuse_lowlevel.h:132
	SetAttrUid = (1 << 1)
	// SetAttrGid as defined in fuse3/fuse_lowlevel.h:133
	SetAttrGid = (1 << 2)
	// SetAttrSize as defined in fuse3/fuse_lowlevel.h:134
	SetAttrSize = (1 << 3)
	// SetAttrAtime as defined in fuse3/fuse_lowlevel.h:135
	SetAttrAtime = (1 << 4)
	// SetAttrMtime as defined in fuse3/fuse_lowlevel.h:136
	SetAttrMtime = (1 << 5)
	// SetAttrAtimeNow as defined in fuse3/fuse_lowlevel.h:137
	SetAttrAtimeNow = (1 << 7)
	// SetAttrMtimeNow as defined in fuse3/fuse_lowlevel.h:138
	SetAttrMtimeNow = (1 << 8)
	// SetAttrCtime as defined in fuse3/fuse_lowlevel.h:139
	SetAttrCtime = (1 << 10)
	// MajorVersion as defined in fuse3/fuse_common.h:23
	MajorVersion = 3
	// MinorVersion as defined in fuse3/fuse_common.h:26
	MinorVersion = 10
	// Version as defined in fuse3/fuse_common.h:29
	Version = 310
	// CapAsyncRead as defined in fuse3/fuse_common.h:141
	CapAsyncRead = (1 << 0)
	// CapPosixLocks as defined in fuse3/fuse_common.h:149
	CapPosixLocks = (1 << 1)
	// CapAtomicOTrunc as defined in fuse3/fuse_common.h:158
	CapAtomicOTrunc = (1 << 3)
	// CapExportSupport as defined in fuse3/fuse_common.h:165
	CapExportSupport = (1 << 4)
	// CapDontMask as defined in fuse3/fuse_common.h:173
	CapDontMask = (1 << 6)
	// CapSpliceWrite as defined in fuse3/fuse_common.h:181
	CapSpliceWrite = (1 << 7)
	// CapSpliceMove as defined in fuse3/fuse_common.h:189
	CapSpliceMove = (1 << 8)
	// CapSpliceRead as defined in fuse3/fuse_common.h:198
	CapSpliceRead = (1 << 9)
	// CapFlockLocks as defined in fuse3/fuse_common.h:211
	CapFlockLocks = (1 << 10)
	// CapIoctlDir as defined in fuse3/fuse_common.h:218
	CapIoctlDir = (1 << 11)
	// CapAutoInvalData as defined in fuse3/fuse_common.h:240
	CapAutoInvalData = (1 << 12)
	// CapReaddirplus as defined in fuse3/fuse_common.h:248
	CapReaddirplus = (1 << 13)
	// CapReaddirplusAuto as defined in fuse3/fuse_common.h:276
	CapReaddirplusAuto = (1 << 14)
	// CapAsyncDio as defined in fuse3/fuse_common.h:287
	CapAsyncDio = (1 << 15)
	// CapWritebackCache as defined in fuse3/fuse_common.h:296
	CapWritebackCache = (1 << 16)
	// CapNoOpenSupport as defined in fuse3/fuse_common.h:309
	CapNoOpenSupport = (1 << 17)
	// CapParallelDirops as defined in fuse3/fuse_common.h:319
	CapParallelDirops = (1 << 18)
	// CapPosixAcl as defined in fuse3/fuse_common.h:338
	CapPosixAcl = (1 << 19)
	// CapHandleKillpriv as defined in fuse3/fuse_common.h:347
	CapHandleKillpriv = (1 << 20)
	// CapCacheSymlinks as defined in fuse3/fuse_common.h:360
	CapCacheSymlinks = (1 << 23)
	// CapNoOpendirSupport as defined in fuse3/fuse_common.h:372
	CapNoOpendirSupport = (1 << 24)
	// CapExplicitInvalData as defined in fuse3/fuse_common.h:395
	CapExplicitInvalData = (1 << 25)
	// IoctlCompat as defined in fuse3/fuse_common.h:407
	IoctlCompat = (1 << 0)
	// IoctlUnrestricted as defined in fuse3/fuse_common.h:408
	IoctlUnrestricted = (1 << 1)
	// IoctlRetry as defined in fuse3/fuse_common.h:409
	IoctlRetry = (1 << 2)
	// IoctlDir as defined in fuse3/fuse_common.h:410
	IoctlDir = (1 << 4)
	// IoctlMaxIov as defined in fuse3/fuse_common.h:412
	IoctlMaxIov = 256
	// OptKeyOpt as defined in fuse3/fuse_opt.h:129
	OptKeyOpt = -1
	// OptKeyNonopt as defined in fuse3/fuse_opt.h:137
	OptKeyNonopt = -2
	// OptKeyKeep as defined in fuse3/fuse_opt.h:145
	OptKeyKeep = -3
	// OptKeyDiscard as defined in fuse3/fuse_opt.h:153
	OptKeyDiscard = -4
)

// BufFlags as declared in fuse3/fuse_common.h:626
type BufFlags int32

// BufFlags enumeration from fuse3/fuse_common.h:626
const (
	BufIsFd    = 2
	BufFdSeek  = 4
	BufFdRetry = 8
)

// BufCopyFlags as declared in fuse3/fuse_common.h:657
type BufCopyFlags int32

// BufCopyFlags enumeration from fuse3/fuse_common.h:657
const (
	BufNoSplice       = 2
	BufForceSplice    = 4
	BufSpliceMove     = 8
	BufSpliceNonblock = 16
)

// LogLevel as declared in fuse3/fuse_log.h:28
type LogLevel int32

// LogLevel enumeration from fuse3/fuse_log.h:28
const (
	LogEmerg   = iota
	LogAlert   = 1
	LogCrit    = 2
	LogErr     = 3
	LogWarning = 4
	LogNotice  = 5
	LogInfo    = 6
	LogDebug   = 7
)

const ()
