// WARNING: This file has automatically been generated on Fri, 20 May 2022 19:39:49 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cuse

/*
#cgo pkg-config: fuse3
#include <cuse_lowlevel.h>
#include <fuse_lowlevel.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// LowlevelMain function as declared in fuse3/cuse_lowlevel.h:80
func LowlevelMain(argc int32, argv [][]byte, ci []Info, clop []LowlevelOps, userdata unsafe.Pointer) int32 {
	cargc, cargcAllocMap := (C.int)(argc), cgoAllocsUnknown
	cargv, cargvAllocMap := unpackArgSSByte(argv)
	cci, cciAllocMap := unpackArgSInfo(ci)
	cclop, cclopAllocMap := unpackArgSLowlevelOps(clop)
	cuserdata, cuserdataAllocMap := userdata, cgoAllocsUnknown
	__ret := C.cuse_lowlevel_main(cargc, cargv, cci, cclop, cuserdata)
	runtime.KeepAlive(cuserdataAllocMap)
	packSLowlevelOps(clop, cclop)
	runtime.KeepAlive(cclopAllocMap)
	packSInfo(ci, cci)
	runtime.KeepAlive(cciAllocMap)
	packSSByte(argv, cargv)
	runtime.KeepAlive(cargvAllocMap)
	runtime.KeepAlive(cargcAllocMap)
	__v := (int32)(__ret)
	return __v
}

// PollhandleDestroy function as declared in fuse3/fuse_common.h:617
func PollhandleDestroy(ph []Pollhandle) {
	cph, cphAllocMap := copyPStructFusePollhandleBytes((*sliceHeader)(unsafe.Pointer(&ph)))
	C.fuse_pollhandle_destroy(cph)
	runtime.KeepAlive(cphAllocMap)
}
