// WARNING: This file has automatically been generated on Thu, 19 May 2022 22:32:28 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cuse

/*
#cgo pkg-config: fuse3
#include <cuse_lowlevel.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Ino type as declared in fuse3/fuse_lowlevel.h:46
type Ino uint32

// Req as declared in fuse3/fuse_lowlevel.h:49
type Req C.fuse_req_t

// InterruptFunc type as declared in fuse3/fuse_lowlevel.h:1821
type InterruptFunc func(req Req, data unsafe.Pointer)

// OptProc type as declared in fuse3/fuse_opt.h:180
type OptProc func(data unsafe.Pointer, arg string, key int32, outargs []Args) int32

// LogFunc type as declared in fuse3/fuse_log.h:52
type LogFunc func(level LogLevel, fmt string, ap unsafe.Pointer)

// Info as declared in fuse3/cuse_lowlevel.h:33
type Info struct {
	DevMajor       uint32
	DevMinor       uint32
	DevInfoArgc    uint32
	DevInfoArgv    []string
	Flags          uint32
	ref30ec17cc    *C.struct_cuse_info
	allocs30ec17cc interface{}
}

// LowlevelOps as declared in fuse3/cuse_lowlevel.h:49
type LowlevelOps struct {
	Init           *func(userdata unsafe.Pointer, conn []ConnInfo)
	InitDone       *func(userdata unsafe.Pointer)
	Destroy        *func(userdata unsafe.Pointer)
	Open           *func(req Req, fi []FileInfo)
	Read           *func(req Req, size uint32, off int32, fi []FileInfo)
	Write          *func(req Req, buf string, size uint32, off int32, fi []FileInfo)
	Flush          *func(req Req, fi []FileInfo)
	Release        *func(req Req, fi []FileInfo)
	Fsync          *func(req Req, datasync int32, fi []FileInfo)
	Ioctl          *func(req Req, cmd int32, arg unsafe.Pointer, fi []FileInfo, flags uint32, inBuf unsafe.Pointer, inBufsz uint32, outBufsz uint32)
	Poll           *func(req Req, fi []FileInfo, ph []Pollhandle)
	refa7a7b71f    *C.struct_cuse_lowlevel_ops
	allocsa7a7b71f interface{}
}

// Args as declared in fuse3/fuse_opt.h:109
type Args struct {
	Argc           int32
	Argv           [][]byte
	Allocated      int32
	refa7e94d76    *C.struct_fuse_args
	allocsa7e94d76 interface{}
}

// Buf as declared in fuse3/fuse_common.h:702
type Buf struct {
	Size           uint32
	Flags          BufFlags
	Mem            unsafe.Pointer
	Fd             int32
	Pos            int32
	refbb017fb9    *C.struct_fuse_buf
	allocsbb017fb9 interface{}
}

// Bufvec as declared in fuse3/fuse_common.h:743
type Bufvec struct {
	Count          uint32
	Idx            uint32
	Off            uint32
	Buf            [1]Buf
	ref7623f27b    *C.struct_fuse_bufvec
	allocs7623f27b interface{}
}

// CmdlineOpts as declared in fuse3/fuse_lowlevel.h:1871
type CmdlineOpts struct {
	Singlethread     int32
	Foreground       int32
	Debug            int32
	NodefaultSubtype int32
	Mountpoint       []byte
	ShowVersion      int32
	ShowHelp         int32
	CloneFd          int32
	MaxIdleThreads   uint32
	refd34a9b90      *C.struct_fuse_cmdline_opts
	allocsd34a9b90   interface{}
}

// ConnInfo as declared in fuse3/fuse_common.h:421
type ConnInfo struct {
	ProtoMajor          uint32
	ProtoMinor          uint32
	MaxWrite            uint32
	MaxRead             uint32
	MaxReadahead        uint32
	Capable             uint32
	Want                uint32
	MaxBackground       uint32
	CongestionThreshold uint32
	TimeGran            uint32
	Reserved            [22]uint32
	ref2dad4d28         *C.struct_fuse_conn_info
	allocs2dad4d28      interface{}
}

// ConnInfoOpts as declared in fuse3/fuse_common.h:534
type ConnInfoOpts C.struct_fuse_conn_info_opts

// Ctx as declared in fuse3/fuse_lowlevel.h:111
type Ctx struct {
	Uid            uint32
	Gid            uint32
	Pid            int32
	Umask          uint32
	ref59d719ac    *C.struct_fuse_ctx
	allocs59d719ac interface{}
}

// EntryParam as declared in fuse3/fuse_lowlevel.h:59
type EntryParam struct {
	Ino            Ino
	Generation     uint32
	AttrTimeout    float64
	EntryTimeout   float64
	ref66366f4f    *C.struct_fuse_entry_param
	allocs66366f4f interface{}
}

// FileInfo as declared in fuse3/fuse_common.h:44
type FileInfo struct {
	Flags          int32
	Writepage      uint32
	DirectIo       uint32
	KeepCache      uint32
	Flush          uint32
	Nonseekable    uint32
	FlockRelease   uint32
	CacheReaddir   uint32
	Padding        uint32
	Padding2       uint32
	Fh             uint32
	LockOwner      uint32
	PollEvents     uint32
	ref5c0de00a    *C.struct_fuse_file_info
	allocs5c0de00a interface{}
}

// ForgetData as declared in fuse3/fuse_lowlevel.h:125
type ForgetData struct {
	Ino            Ino
	Nlookup        uint32
	refce6ed80b    *C.struct_fuse_forget_data
	allocsce6ed80b interface{}
}

// LoopConfig as declared in fuse3/fuse_common.h:107
type LoopConfig struct {
	CloneFd        int32
	MaxIdleThreads uint32
	refc82c52ea    *C.struct_fuse_loop_config
	allocsc82c52ea interface{}
}

// Opt as declared in fuse3/fuse_opt.h:77
type Opt struct {
	Templ          string
	Offset         uint32
	Value          int32
	ref3d1769e7    *C.struct_fuse_opt
	allocs3d1769e7 interface{}
}

// Pollhandle as declared in fuse3/fuse_common.h:533
type Pollhandle C.struct_fuse_pollhandle

// Session as declared in fuse3/fuse_common.h:532
type Session C.struct_fuse_session
