// WARNING: This file has automatically been generated on Fri, 20 May 2022 19:39:49 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cuse

/*
#cgo pkg-config: fuse3
#include <cuse_lowlevel.h>
#include <fuse_lowlevel.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Req as declared in fuse3/fuse_lowlevel.h:49
type Req C.fuse_req_t

// Info as declared in fuse3/cuse_lowlevel.h:33
type Info struct {
	devMajor       uint32
	devMinor       uint32
	devInfoArgc    uint32
	devInfoArgv    []string
	flags          uint32
	ref30ec17cc    *C.struct_cuse_info
	allocs30ec17cc interface{}
}

// LowlevelOps as declared in fuse3/cuse_lowlevel.h:49
type LowlevelOps struct {
	init           *func(userdata unsafe.Pointer, conn []ConnInfo)
	initDone       *func(userdata unsafe.Pointer)
	destroy        *func(userdata unsafe.Pointer)
	open           *func(req Req, fi []FileInfo)
	read           *func(req Req, size uint32, off int32, fi []FileInfo)
	write          *func(req Req, buf string, size uint32, off int32, fi []FileInfo)
	flush          *func(req Req, fi []FileInfo)
	release        *func(req Req, fi []FileInfo)
	fsync          *func(req Req, datasync int32, fi []FileInfo)
	ioctl          *func(req Req, cmd int32, arg unsafe.Pointer, fi []FileInfo, flags uint32, inBuf unsafe.Pointer, inBufsz uint32, outBufsz uint32)
	poll           *func(req Req, fi []FileInfo, ph []Pollhandle)
	refa7a7b71f    *C.struct_cuse_lowlevel_ops
	allocsa7a7b71f interface{}
}

// ConnInfo as declared in fuse3/fuse_common.h:421
type ConnInfo struct {
	protoMajor          uint32
	protoMinor          uint32
	maxWrite            uint32
	maxRead             uint32
	maxReadahead        uint32
	capable             uint32
	want                uint32
	maxBackground       uint32
	congestionThreshold uint32
	timeGran            uint32
	reserved            [22]uint32
	ref2dad4d28         *C.struct_fuse_conn_info
	allocs2dad4d28      interface{}
}

// ConnInfoOpts as declared in fuse3/fuse_common.h:534
type ConnInfoOpts C.struct_fuse_conn_info_opts

// FileInfo as declared in fuse3/fuse_common.h:44
type FileInfo struct {
	flags          int32
	writepage      uint32
	directIo       uint32
	keepCache      uint32
	flush          uint32
	nonseekable    uint32
	flockRelease   uint32
	cacheReaddir   uint32
	padding        uint32
	padding2       uint32
	fh             uint32
	lockOwner      uint32
	pollEvents     uint32
	ref5c0de00a    *C.struct_fuse_file_info
	allocs5c0de00a interface{}
}

// Pollhandle as declared in fuse3/fuse_common.h:533
type Pollhandle C.struct_fuse_pollhandle
